### ISSUE TITLE
Correcciones en el espaciado de algunos elementos

### ISSUE THREAD

**Issue by miguelmich** [Zirkanyo/Foxy-Test#1]
# Qué?
Algunos elementos están mal posicionados, específicamente aquellos que usan `position: absolute;` acutalmente son relativos al contenedor principal en vez de los que deberían ser sus elementos padres:

Badge de notificaciones del ícono de la campana:
![image](https://user-images.githubusercontent.com/662930/37265206-ddd727a8-257f-11e8-8adf-ddb25fd51f5b.png)

El markup comúnmente usado para este caso sería el siguiente:

```html
<div class="bell-icon">
  <img src="...">
  <span class="notification-count">3</span>
</div>
```

Siendo el `bell-icon` el elemento con `position: relative;` y `notification-count` con `position: absolute;` esto hace que el elemento de la notificación sea relativo a su padre relativo inmediato (en este caso `bell-icon`), al parecer todavía no manejas bien este tema pero dado que es de suma importancia te dejo información al respecto:
https://www.w3schools.com/css/css_positioning.asp
https://css-tricks.com/absolute-positioning-inside-relative-positioning/

Esto también se repite en los elementos de los mensajes:
![image](https://user-images.githubusercontent.com/662930/37265370-dde0bc04-2580-11e8-9676-5c9cd0b7a0b5.png)

En este caso el elemento `rojo` debería de estar dentro del `art_t` y su padre debe de ser relativo para poder usar correctamente la posición absoluta, en este caso no se le puede asignar un `top` o un `left` porque todos los otros dejarían de funcionar al no tener un padre relativo.

**Comment by Zirkanyo** [comment]
Realice los cambios.

**Comment by miguelmich** [comment]
@Zirkanyo ok, pero ten en cuenta que las instrucciones eran diferentes:

Entonces, vamos a hacer estas mejoras de la siguiente manera:

- [x] 1. Por favor acepta la invitación que te envié a tu correo la semana pasada para que ingreses a nuestro canal en slack, si tienes problemas para hacer esto por favor contáctame que con mucho gusto te ayudaré
- [ ] 2. Por cada cambio que haya que hacer tu vas a crear una nueva rama `git checkout -b fix/spacing_issues` en el caso del primero issue
- [ ] 3. Haz los correctivos en la rama, haz commit y luego sube la rama con `git push origin -u fix/spacing_issues`
- [ ] 4. Crear un Pull Request explicando los cambios que has hecho y el proceso de review comenzará aquí
- [ ] 5. Si hay algún feedback adicional tu corregirás de nuevo en esta rama y subirás de nuevo los cambios con `git push`
- [ ] 6. Una vez todos los cambios hayan sido aceptados podrás hacer merge de esta rama en la rama principal (master)

Te fuiste directamente a hacer cambios en la rama de producción, algo que se debe evitar a toda costa y al no utilizar las ramas ni los "pull request" no hubo espacio para hacer un feedback adecuado.

En todo equipo de trabajo es muy importante la comunicación permanente, precisamente para evitar este tipo de situaciones, la capacidad de trabajar en equipo es un skill fundamental en el desarrollo de software.

Entonces para terminar, voy a hacer otra ronda de feedback y si no hay cambios para hacer concluímos aquí, sino por favor sigue las instrucciones y si tienes alguna pregunta para eso estamos en el slack :)
